import './i18n.js'

import './01-static'
import './02-richtext'
import './03-text-alignment-toolbar'
import './04-block-alignment-toolbar'
import './05-custom-toolbar'
import './06-inspector-controls'
import './07-inspector-control-fields'
import './08-form-fields'
import './09-media-upload'
import './10-url-input'
